### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by timosturm** [privacyidea/pi-authenticator#184]
~~~~dart
Error:
NoSuchMethodError: The method 'dependOnInheritedWidgetOfExactType' was called on null. Receiver: null Tried calling: dependOnInheritedWidgetOfExactType()

Stacktrace:
#0 Localizations.of (package:flutter/src/widgets/localizations.dart:455)
#1 Localization.of (package:privacyidea_authenticator/utils/localization_utils.dart:24)
#2 _PushWidgetState._rollOutToken (package:privacyidea_authenticator/widgets/token_widgets.dart:409)
~~~~

Affects: iOS
Notes:

**Comment by timosturm** [comment]
I am not exactly sure how to handle this error. Theoretically, this problem could arise any time the `context` is used. In practice, this almost (apparently) never occurs, as from the flutter side it is not intended to handle such a case.

Wrapping each and every call that uses the context, to check if it is null or not, is not viable either. Therefore, I think it is best to wait if this problem occurs often enough to justify fixing it.
