### ISSUE TITLE
Error on updating firebase token if value is null

### ISSUE THREAD

**Issue by timosturm** [privacyidea/pi-authenticator#193]
Error:
~~~~
Invalid argument(s): Can not send request because the [body] contains a null value, this is not permitted.
~~~~

Stack trace:
~~~~
#0 doPost (package:privacyidea_authenticator/utils/network_utils.dart:58)
#1 _MainScreenState._updateFirebaseToken (package:privacyidea_authenticator/screens/main_screen.dart:632)
~~~~

From inspecting the code it seems to be most likely that the `serial` of the token is null for some reason. If the fbToken was null the method would have returned before making the network request. Because all other elements of the body involve method calls that do not return null at the end, it is not possible for them to be null.

**Comment by timosturm** [comment]
I added more information to the error message that informs about the keys in the body that are null. Therefore, I will close this issue for now as it does not seem to occur often.
