### ISSUE TITLE
Error when showing messages

### ISSUE THREAD

**Issue by timosturm** [privacyidea/pi-authenticator#212]
~~~~dart
Error:
NoSuchMethodError: The method 'dependOnInheritedWidgetOfExactType' was called on null. Receiver: null Tried calling: dependOnInheritedWidgetOfExactType()

Stack trace:
#0 Localizations.of (package:flutter/src/widgets/localizations.dart:455)
#1 Localization.of (package:privacyidea_authenticator/utils/localization_utils.dart:24)
#2 _PushWidgetState._rollOutToken (package:privacyidea_authenticator/widgets/token_widgets.dart:414)
~~~~

We may need to find out, how showing messages to the user can be done more safely. Because, if a widget tries to show a message when the context is not available anymore, it will crash. It remains unknown when such a case occurs.

**Comment by timosturm** [comment]
Duplicate of #184
