### ISSUE TITLE
Polling sometimes causes app-crash

### ISSUE THREAD

**Issue by jacekwiczkowski** [privacyidea/pi-authenticator#240]
Stack trace:
#0 IOClient.send (package:http/src/io_client.dart:62)

#1 BaseClient._sendUnstreamed (package:http/src/base_client.dart:91)

#2 doGet (package:privacyidea_authenticator/utils/network_utils.dart:121)

#3 _MainScreenState._pollForRequests (package:privacyidea_authenticator/screens/main_screen.dart:212)

**Comment by jacekwiczkowski** [comment]
#248 catches the exception
