### ISSUE TITLE
((4.0.0) Error report: >> _TypeError: type 'Null' is not a subtype of type 'FutureOr<String>'<<) 

### ISSUE THREAD

**Issue by jacekwiczkowski** [privacyidea/pi-authenticator#259]
catch the exception

**Comment by jacekwiczkowski** [comment]
Stack trace:
#0 Legacy.sign (package:pi_authenticator_legacy/pi_authenticator_legacy.dart:42)

#1 PushProvider._updateFirebaseToken (package:privacyidea_authenticator/utils/push_provider.dart:290)
