### ISSUE TITLE
PlatformException: PlatformException(auth_in_progress, Authentication in progress, null, null)

### ISSUE THREAD

**Issue by frankmer** [privacyidea/pi-authenticator#309]
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177)
#2 LocalAuthentication.authenticate (package:local_auth/local_auth.dart:124)
#3 _TokenWidgetState._unlock (package:privacyidea_authenticator/widgets/token_widgets.dart:256)
#4 _TotpWidgetState._buildNonClickableTile. (package:privacyidea_authenticator/widgets/token_widgets.dart:1145)

**Comment by frankmer** [comment]
fixed by checking if an authentication is currently in progress
