### ISSUE TITLE
Uncaught Error: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by frankmer** [privacyidea/pi-authenticator#321]
It seems that _handleIncomingAuthRequest cannot handle null values.
Fix this by refactoring the code to support null-safety.

--------------------------------------------------------------------------------------------------------------------------------------------
[ERROR] (2023-10-09 09:31:05.022542) Uncaught Error: type 'Null' is not a subtype of type 'String'
[ERROR] type 'Null' is not a subtype of type 'String'
[ERROR] Stacktrace:
[ERROR] #0 PushRequestNotifier._handleIncomingRequest (package:privacyidea_authenticator/state_notifiers/push_request_notifier.dart:93)
[ERROR] #1 PushRequestNotifier._handleIncomingAuthRequest.<anonymous closure> (package:privacyidea_authenticator/state_notifiers/push_request_notifier.dart:66)
[ERROR] #2 Mutex.protect (package:mutex/src/mutex.dart:79)
[ERROR] <asynchronous suspension>
[ERROR] #3 PushRequestNotifier._handleIncomingAuthRequest (package:privacyidea_authenticator/state_notifiers/push_request_notifier.dart:64)
[ERROR] <asynchronous suspension>

**Comment by frankmer** [comment]
Nullcheck for every value of the required keys.
